// This file is auto-generated by @hey-api/openapi-ts

export const GitHubAppInstallationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Team Id'
        },
        installation_id: {
            type: 'integer',
            title: 'Installation Id'
        },
        account_login: {
            type: 'string',
            title: 'Account Login'
        },
        account_type: {
            type: 'string',
            title: 'Account Type'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'team_id', 'installation_id', 'account_login', 'account_type'],
    title: 'GitHubAppInstallationPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InstallCallbackBodySchema = {
    properties: {
        installation_id: {
            type: 'integer',
            minimum: 1,
            title: 'Installation Id'
        },
        setup_action: {
            type: 'string',
            maxLength: 64,
            title: 'Setup Action'
        },
        state: {
            type: 'string',
            minLength: 1,
            title: 'State'
        }
    },
    type: 'object',
    required: ['installation_id', 'setup_action', 'state'],
    title: 'InstallCallbackBody'
} as const;

export const InstallUrlResponseSchema = {
    properties: {
        install_url: {
            type: 'string',
            title: 'Install Url'
        },
        state: {
            type: 'string',
            title: 'State'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['install_url', 'state', 'expires_at'],
    title: 'InstallUrlResponse'
} as const;

export const InviteIssuedSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['code', 'url', 'expires_at'],
    title: 'InviteIssued'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LoginBodySchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'LoginBody'
} as const;

export const MemberRoleUpdateSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/TeamRole'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'MemberRoleUpdate'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotificationKindSchema = {
    type: 'string',
    enum: ['workflow_run_started', 'workflow_run_succeeded', 'workflow_run_failed', 'workflow_step_completed', 'team_invite_accepted', 'project_created', 'system'],
    title: 'NotificationKind'
} as const;

export const NotificationPreferencePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        workflow_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow Id'
        },
        event_type: {
            '$ref': '#/components/schemas/NotificationKind'
        },
        in_app: {
            type: 'boolean',
            title: 'In App'
        },
        push: {
            type: 'boolean',
            title: 'Push'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'event_type', 'in_app', 'push'],
    title: 'NotificationPreferencePublic'
} as const;

export const NotificationPreferencePutSchema = {
    properties: {
        in_app: {
            type: 'boolean',
            title: 'In App',
            default: true
        },
        push: {
            type: 'boolean',
            title: 'Push',
            default: false
        }
    },
    type: 'object',
    title: 'NotificationPreferencePut',
    description: `PUT body for /api/v1/notifications/preferences/{event_type}.

The \`\`event_type\`\` is taken from the URL path; the body only carries
the channel toggles. The route always upserts the team-default row
(workflow_id IS NULL) — per-workflow overrides ship in a future slice
when the workflow detail page lands.`
} as const;

export const NotificationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        kind: {
            '$ref': '#/components/schemas/NotificationKind'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload'
        },
        read_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Read At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        source_team_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Team Id'
        },
        source_project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Project Id'
        },
        source_workflow_run_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Workflow Run Id'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'kind', 'payload'],
    title: 'NotificationPublic'
} as const;

export const NotificationReadAllResponseSchema = {
    properties: {
        affected: {
            type: 'integer',
            title: 'Affected'
        }
    },
    type: 'object',
    required: ['affected'],
    title: 'NotificationReadAllResponse'
} as const;

export const NotificationUnreadCountSchema = {
    properties: {
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['count'],
    title: 'NotificationUnreadCount'
} as const;

export const NotificationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotificationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'NotificationsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        installation_id: {
            type: 'integer',
            minimum: 1,
            title: 'Installation Id'
        },
        github_repo_full_name: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Github Repo Full Name'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['installation_id', 'github_repo_full_name', 'name'],
    title: 'ProjectCreate'
} as const;

export const ProjectPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Team Id'
        },
        installation_id: {
            type: 'integer',
            title: 'Installation Id'
        },
        github_repo_full_name: {
            type: 'string',
            title: 'Github Repo Full Name'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        last_push_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Push Status'
        },
        last_push_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Push Error'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'team_id', 'installation_id', 'github_repo_full_name', 'name'],
    title: 'ProjectPublic'
} as const;

export const ProjectPushRulePublicSchema = {
    properties: {
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        mode: {
            type: 'string',
            title: 'Mode'
        },
        branch_pattern: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch Pattern'
        },
        workflow_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['project_id', 'mode'],
    title: 'ProjectPushRulePublic'
} as const;

export const ProjectPushRulePutSchema = {
    properties: {
        mode: {
            type: 'string',
            maxLength: 32,
            minLength: 1,
            title: 'Mode'
        },
        branch_pattern: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch Pattern'
        },
        workflow_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow Id'
        }
    },
    type: 'object',
    required: ['mode'],
    title: 'ProjectPushRulePut',
    description: `PUT body for /api/v1/projects/{id}/push-rule.

Mode-specific field validation runs in the route — the model-level shape
only enforces the str-typing of the fields. The route returns 422 with a
field-specific detail for mismatches (e.g. mode=rule without
branch_pattern).`
} as const;

export const ProjectUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ProjectUpdate',
    description: 'PATCH body for /api/v1/projects/{id} — name only today.'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic'
} as const;

export const SignupBodySchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'SignupBody'
} as const;

export const SystemSettingGenerateResponseSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        value: {
            type: 'string',
            title: 'Value'
        },
        has_value: {
            type: 'boolean',
            title: 'Has Value',
            default: true
        },
        generated: {
            type: 'boolean',
            title: 'Generated',
            default: true
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['key', 'value'],
    title: 'SystemSettingGenerateResponse'
} as const;

export const SystemSettingPublicSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        sensitive: {
            type: 'boolean',
            title: 'Sensitive'
        },
        has_value: {
            type: 'boolean',
            title: 'Has Value'
        },
        value: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Value'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['key', 'sensitive', 'has_value'],
    title: 'SystemSettingPublic'
} as const;

export const SystemSettingPutSchema = {
    properties: {
        value: {
            title: 'Value'
        }
    },
    type: 'object',
    required: ['value'],
    title: 'SystemSettingPut'
} as const;

export const SystemSettingPutResponseSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        value: {
            title: 'Value'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        warnings: {
            items: {
                '$ref': '#/components/schemas/SystemSettingShrinkWarning'
            },
            type: 'array',
            title: 'Warnings',
            default: []
        }
    },
    type: 'object',
    required: ['key', 'value'],
    title: 'SystemSettingPutResponse'
} as const;

export const SystemSettingShrinkWarningSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Team Id'
        },
        size_gb: {
            type: 'integer',
            title: 'Size Gb'
        },
        usage_bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Usage Bytes'
        }
    },
    type: 'object',
    required: ['user_id', 'team_id', 'size_gb'],
    title: 'SystemSettingShrinkWarning'
} as const;

export const TeamCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'TeamCreate'
} as const;

export const TeamMemberPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/TeamRole'
        }
    },
    type: 'object',
    required: ['user_id', 'email', 'role'],
    title: 'TeamMemberPublic'
} as const;

export const TeamMembersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TeamMemberPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TeamMembersPublic'
} as const;

export const TeamMirrorPatchSchema = {
    properties: {
        always_on: {
            type: 'boolean',
            title: 'Always On'
        }
    },
    type: 'object',
    required: ['always_on'],
    title: 'TeamMirrorPatch',
    description: 'PATCH body for /api/v1/teams/{id}/mirror — only `always_on` toggles today.'
} as const;

export const TeamMirrorVolumePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Team Id'
        },
        volume_path: {
            type: 'string',
            title: 'Volume Path'
        },
        container_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Container Id'
        },
        last_started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Started At'
        },
        last_idle_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Idle At'
        },
        always_on: {
            type: 'boolean',
            title: 'Always On'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'team_id', 'volume_path', 'always_on'],
    title: 'TeamMirrorVolumePublic'
} as const;

export const TeamRoleSchema = {
    type: 'string',
    enum: ['member', 'admin'],
    title: 'TeamRole'
} as const;

export const TeamWithRoleSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        is_personal: {
            type: 'boolean',
            title: 'Is Personal'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        role: {
            '$ref': '#/components/schemas/TeamRole'
        }
    },
    type: 'object',
    required: ['id', 'name', 'slug', 'is_personal', 'role'],
    title: 'TeamWithRole'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'user'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'user'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['user', 'system_admin'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'user'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;