// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AdminReadAllTeamsData, AdminReadAllTeamsResponse, AdminReadAdminTeamMembersData, AdminReadAdminTeamMembersResponse, AdminPromoteSystemAdminData, AdminPromoteSystemAdminResponse, AuthSignupData, AuthSignupResponse, AuthLoginData, AuthLoginResponse, AuthLogoutResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, TeamsReadTeamsResponse, TeamsCreateTeamData, TeamsCreateTeamResponse, TeamsReadTeamMembersData, TeamsReadTeamMembersResponse, TeamsInviteToTeamData, TeamsInviteToTeamResponse, TeamsJoinTeamData, TeamsJoinTeamResponse, TeamsUpdateMemberRoleData, TeamsUpdateMemberRoleResponse, TeamsRemoveMemberData, TeamsRemoveMemberResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class AdminService {
    /**
     * Read All Teams
     * List every team in the system, paginated, ordered by created_at DESC.
     *
     * Returns `{data: [TeamPublic, ...], count: int}` where `count` is the
     * unfiltered total (so the FE can render Prev/Next correctly even with
     * skip/limit applied). Mirrors the count+skip/limit pattern in
     * `users.py::read_users`.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readAllTeams(data: AdminReadAllTeamsData = {}): CancelablePromise<AdminReadAllTeamsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/teams',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Admin Team Members
     * Return the roster of any team — does NOT require caller membership.
     *
     * - 404 if team missing.
     * - 200 `{data: [{user_id, email, full_name, role}, ...], count: int}`.
     *
     * Note: deliberately does not call `_assert_caller_is_team_member` from
     * teams.py — system admin must be able to inspect teams they aren't on.
     * @param data The data for the request.
     * @param data.teamId
     * @returns TeamMembersPublic Successful Response
     * @throws ApiError
     */
    public static readAdminTeamMembers(data: AdminReadAdminTeamMembersData): CancelablePromise<AdminReadAdminTeamMembersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/teams/{team_id}/members',
            path: {
                team_id: data.teamId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Promote System Admin
     * Promote a user to UserRole.system_admin. Idempotent.
     *
     * - 404 if target user does not exist.
     * - 200 with the (possibly unchanged) UserPublic on success.
     * - If the target is already system_admin, no DB write is performed and
     * the log line records `already_admin=true`.
     *
     * Demotion (system_admin → user) is intentionally not exposed — out of
     * scope for S05. A future slice can add it with last-admin guards.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static promoteSystemAdmin(data: AdminPromoteSystemAdminData): CancelablePromise<AdminPromoteSystemAdminResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/admin/users/{user_id}/promote-system-admin',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class AuthService {
    /**
     * Signup
     * Create a new user + personal team atomically, set session cookie, return UserPublic.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static signup(data: AuthSignupData): CancelablePromise<AuthSignupResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Login
     * Validate credentials, set session cookie, return UserPublic.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static login(data: AuthLoginData): CancelablePromise<AuthLoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/login',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Logout
     * Clear the session cookie. Idempotent — works without an existing cookie.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static logout(): CancelablePromise<AuthLogoutResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/logout'
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class TeamsService {
    /**
     * Read Teams
     * Return all teams the caller is a member of with their role.
     *
     * Single SELECT JOIN — no N+1. Filtered by the caller's user_id so the
     * endpoint can never leak teams the caller is not a member of.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readTeams(): CancelablePromise<TeamsReadTeamsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/teams/'
        });
    }
    
    /**
     * Create Team
     * Create a non-personal team with the caller as admin. Returns TeamWithRole.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TeamWithRole Successful Response
     * @throws ApiError
     */
    public static createTeam(data: TeamsCreateTeamData): CancelablePromise<TeamsCreateTeamResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/teams/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Team Members
     * Return the roster of a team the caller is a member of.
     *
     * - 404 if team missing.
     * - 403 if caller is not a member of the team.
     * - 200 `{data: [{user_id, email, full_name, role}, ...], count: int}`.
     * @param data The data for the request.
     * @param data.teamId
     * @returns TeamMembersPublic Successful Response
     * @throws ApiError
     */
    public static readTeamMembers(data: TeamsReadTeamMembersData): CancelablePromise<TeamsReadTeamMembersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/teams/{team_id}/members',
            path: {
                team_id: data.teamId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Invite To Team
     * Issue a bearer-token invite to join a non-personal team.
     *
     * - 404 if team missing.
     * - 403 if caller is not a member, or is a member but not an admin.
     * - 403 "Cannot invite to personal teams" if team.is_personal.
     * - 200 with {code, url, expires_at} on success.
     * @param data The data for the request.
     * @param data.teamId
     * @returns InviteIssued Successful Response
     * @throws ApiError
     */
    public static inviteToTeam(data: TeamsInviteToTeamData): CancelablePromise<TeamsInviteToTeamResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/teams/{team_id}/invite',
            path: {
                team_id: data.teamId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Join Team
     * Accept an invite code — atomically add caller as a member of the team.
     *
     * - 404 if code unknown.
     * - 410 if invite expired or already used.
     * - 409 if caller is already a member of the team.
     * - 200 TeamWithRole on success.
     * @param data The data for the request.
     * @param data.code
     * @returns TeamWithRole Successful Response
     * @throws ApiError
     */
    public static joinTeam(data: TeamsJoinTeamData): CancelablePromise<TeamsJoinTeamResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/teams/join/{code}',
            path: {
                code: data.code
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Member Role
     * Promote or demote a team member's role.
     *
     * - 404 if team or target membership is missing.
     * - 403 if caller is not an admin on the team.
     * - 400 if the mutation would leave the team with zero admins.
     * - 200 TeamWithRole on success (echoes the target's new role).
     * @param data The data for the request.
     * @param data.teamId
     * @param data.userId
     * @param data.requestBody
     * @returns TeamWithRole Successful Response
     * @throws ApiError
     */
    public static updateMemberRole(data: TeamsUpdateMemberRoleData): CancelablePromise<TeamsUpdateMemberRoleResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/teams/{team_id}/members/{user_id}/role',
            path: {
                team_id: data.teamId,
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Remove Member
     * Remove a member from a team.
     *
     * - 404 if team or target membership is missing.
     * - 403 if caller is not an admin on the team.
     * - 400 if team is personal (personal teams are owner-scoped by construction).
     * - 400 if target is the sole remaining admin.
     * - 204 on success (empty body).
     * @param data The data for the request.
     * @param data.teamId
     * @param data.userId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static removeMember(data: TeamsRemoveMemberData): CancelablePromise<TeamsRemoveMemberResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/teams/{team_id}/members/{user_id}',
            path: {
                team_id: data.teamId,
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}