// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InviteIssued = {
    code: string;
    url: string;
    expires_at: string;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LoginBody = {
    email: string;
    password: string;
};

export type MemberRoleUpdate = {
    role: TeamRole;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SignupBody = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type TeamCreate = {
    name: string;
};

export type TeamMemberPublic = {
    user_id: string;
    email: string;
    full_name?: (string | null);
    role: TeamRole;
};

export type TeamMembersPublic = {
    data: Array<TeamMemberPublic>;
    count: number;
};

export type TeamRole = 'member' | 'admin';

export type TeamWithRole = {
    id: string;
    name: string;
    slug: string;
    is_personal: boolean;
    created_at?: (string | null);
    role: TeamRole;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRole = 'user' | 'system_admin';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminReadAllTeamsData = {
    limit?: number;
    skip?: number;
};

export type AdminReadAllTeamsResponse = ({
    [key: string]: unknown;
});

export type AdminReadAdminTeamMembersData = {
    teamId: string;
};

export type AdminReadAdminTeamMembersResponse = (TeamMembersPublic);

export type AdminPromoteSystemAdminData = {
    userId: string;
};

export type AdminPromoteSystemAdminResponse = (UserPublic);

export type AuthSignupData = {
    requestBody: SignupBody;
};

export type AuthSignupResponse = (UserPublic);

export type AuthLoginData = {
    requestBody: LoginBody;
};

export type AuthLoginResponse = (UserPublic);

export type AuthLogoutResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TeamsReadTeamsResponse = ({
    [key: string]: unknown;
});

export type TeamsCreateTeamData = {
    requestBody: TeamCreate;
};

export type TeamsCreateTeamResponse = (TeamWithRole);

export type TeamsReadTeamMembersData = {
    teamId: string;
};

export type TeamsReadTeamMembersResponse = (TeamMembersPublic);

export type TeamsInviteToTeamData = {
    teamId: string;
};

export type TeamsInviteToTeamResponse = (InviteIssued);

export type TeamsJoinTeamData = {
    code: string;
};

export type TeamsJoinTeamResponse = (TeamWithRole);

export type TeamsUpdateMemberRoleData = {
    requestBody: MemberRoleUpdate;
    teamId: string;
    userId: string;
};

export type TeamsUpdateMemberRoleResponse = (TeamWithRole);

export type TeamsRemoveMemberData = {
    teamId: string;
    userId: string;
};

export type TeamsRemoveMemberResponse = (void);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);