// This file is auto-generated by @hey-api/openapi-ts

export type GitHubAppInstallationPublic = {
    id: string;
    team_id: string;
    installation_id: number;
    account_login: string;
    account_type: string;
    created_at?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InstallCallbackBody = {
    installation_id: number;
    setup_action: string;
    state: string;
};

export type InstallUrlResponse = {
    install_url: string;
    state: string;
    expires_at: string;
};

export type InviteIssued = {
    code: string;
    url: string;
    expires_at: string;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LoginBody = {
    email: string;
    password: string;
};

export type MemberRoleUpdate = {
    role: TeamRole;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationKind = 'workflow_run_started' | 'workflow_run_succeeded' | 'workflow_run_failed' | 'workflow_step_completed' | 'team_invite_accepted' | 'project_created' | 'system';

export type NotificationPreferencePublic = {
    id: string;
    user_id: string;
    workflow_id?: (string | null);
    event_type: NotificationKind;
    in_app: boolean;
    push: boolean;
    created_at?: (string | null);
    updated_at?: (string | null);
};

/**
 * PUT body for /api/v1/notifications/preferences/{event_type}.
 *
 * The ``event_type`` is taken from the URL path; the body only carries
 * the channel toggles. The route always upserts the team-default row
 * (workflow_id IS NULL) — per-workflow overrides ship in a future slice
 * when the workflow detail page lands.
 */
export type NotificationPreferencePut = {
    in_app?: boolean;
    push?: boolean;
};

export type NotificationPublic = {
    id: string;
    user_id: string;
    kind: NotificationKind;
    payload: {
        [key: string]: unknown;
    };
    read_at?: (string | null);
    created_at?: (string | null);
    source_team_id?: (string | null);
    source_project_id?: (string | null);
    source_workflow_run_id?: (string | null);
};

export type NotificationReadAllResponse = {
    affected: number;
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
};

/**
 * POST /api/v1/notifications/test body — system-admin seed trigger.
 *
 * Inserts a notification row for the recipient (defaults to the calling
 * admin when ``user_id`` is omitted). Used to prove the bell wiring without
 * depending on a real invite/project flow. ``kind`` defaults to ``system``;
 * M005/S02/T05 widened it to optionally accept any NotificationKind so the
 * preferences contract spec can fire a `team_invite_accepted` and assert
 * that a preference toggle actually suppresses the in_app insert.
 */
export type NotificationTestTrigger = {
    user_id?: (string | null);
    message?: string;
    kind?: NotificationKind;
};

export type NotificationUnreadCount = {
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    installation_id: number;
    github_repo_full_name: string;
    name: string;
};

export type ProjectPublic = {
    id: string;
    team_id: string;
    installation_id: number;
    github_repo_full_name: string;
    name: string;
    last_push_status?: (string | null);
    last_push_error?: (string | null);
    created_at?: (string | null);
};

export type ProjectPushRulePublic = {
    project_id: string;
    mode: string;
    branch_pattern?: (string | null);
    workflow_id?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

/**
 * PUT body for /api/v1/projects/{id}/push-rule.
 *
 * Mode-specific field validation runs in the route — the model-level shape
 * only enforces the str-typing of the fields. The route returns 422 with a
 * field-specific detail for mismatches (e.g. mode=rule without
 * branch_pattern).
 */
export type ProjectPushRulePut = {
    mode: string;
    branch_pattern?: (string | null);
    workflow_id?: (string | null);
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

/**
 * PATCH body for /api/v1/projects/{id} — name only today.
 */
export type ProjectUpdate = {
    name: string;
};

/**
 * POST /api/v1/push/subscribe body — full T03 wiring lands here.
 *
 * Shape matches ``PushSubscription.toJSON()`` from the browser. T01 only
 * declares the model so the migration test imports are coherent; the
 * subscribe route ships in T03.
 */
export type PushSubscriptionCreate = {
    endpoint: string;
    keys: PushSubscriptionKeys;
};

/**
 * DELETE /api/v1/push/subscribe body — endpoint-only.
 *
 * The browser's ``PushSubscription.unsubscribe()`` does not return the
 * ``keys`` material, so the unsubscribe path takes only the endpoint URL
 * and uses (user_id, endpoint) as the deletion key.
 */
export type PushSubscriptionDelete = {
    endpoint: string;
};

/**
 * Browser-issued ECDH key material for Web Push message encryption.
 *
 * Shape mirrors ``PushSubscription.toJSON().keys`` from the W3C Push API.
 * Both halves are url-safe-base64 strings; we don't validate base64 at the
 * API boundary — pywebpush surfaces a structured error at encrypt time if
 * the bytes are malformed.
 */
export type PushSubscriptionKeys = {
    p256dh: string;
    auth: string;
};

/**
 * Redaction-safe projection of a PushSubscription row.
 *
 * NEVER include the raw ``endpoint`` — only ``endpoint_hash`` (the leading
 * 8 chars of sha256(endpoint)). The hash is enough for the operator UI to
 * distinguish two devices and for log-cross-correlation, without leaking
 * the push URL itself (which is treated as a bearer-style secret).
 */
export type PushSubscriptionPublic = {
    id: string;
    endpoint_hash: string;
    user_agent?: (string | null);
    created_at?: (string | null);
    last_seen_at?: (string | null);
};

export type PushSubscriptionsList = {
    data: Array<PushSubscriptionPublic>;
    count: number;
};

export type SignupBody = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type SystemSettingGenerateResponse = {
    key: string;
    value: string;
    has_value?: boolean;
    generated?: boolean;
    updated_at?: (string | null);
};

export type SystemSettingPublic = {
    key: string;
    sensitive: boolean;
    has_value: boolean;
    value?: (unknown | null);
    updated_at?: (string | null);
};

export type SystemSettingPut = {
    value: unknown;
};

export type SystemSettingPutResponse = {
    key: string;
    value: unknown;
    updated_at?: (string | null);
    warnings?: Array<SystemSettingShrinkWarning>;
};

export type SystemSettingShrinkWarning = {
    user_id: string;
    team_id: string;
    size_gb: number;
    usage_bytes?: (number | null);
};

export type TeamCreate = {
    name: string;
};

export type TeamMemberPublic = {
    user_id: string;
    email: string;
    full_name?: (string | null);
    role: TeamRole;
};

export type TeamMembersPublic = {
    data: Array<TeamMemberPublic>;
    count: number;
};

/**
 * PATCH body for /api/v1/teams/{id}/mirror — only `always_on` toggles today.
 */
export type TeamMirrorPatch = {
    always_on: boolean;
};

export type TeamMirrorVolumePublic = {
    id: string;
    team_id: string;
    volume_path: string;
    container_id?: (string | null);
    last_started_at?: (string | null);
    last_idle_at?: (string | null);
    always_on: boolean;
    created_at?: (string | null);
};

export type TeamRole = 'member' | 'admin';

export type TeamWithRole = {
    id: string;
    name: string;
    slug: string;
    is_personal: boolean;
    created_at?: (string | null);
    role: TeamRole;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRole = 'user' | 'system_admin';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Response for POST /admin/settings/vapid_keys/generate.
 *
 * Returns BOTH the public and private VAPID keys exactly once. Subsequent
 * admin GETs on either row return the redacted shape (public is plain JSONB
 * and remains visible; private has ``value=null, has_value=true``).
 * Re-calling the endpoint is intentionally destructive (D025) — every
 * existing push subscription becomes unverifiable until devices re-subscribe.
 */
export type VapidKeysGenerateResponse = {
    public_key: string;
    private_key: string;
    overwrote_existing: boolean;
};

/**
 * Response for GET /api/v1/push/vapid_public_key (no auth).
 */
export type VapidPublicKeyResponse = {
    public_key: string;
};

export type AdminReadAllTeamsData = {
    limit?: number;
    skip?: number;
};

export type AdminReadAllTeamsResponse = ({
    [key: string]: unknown;
});

export type AdminReadAdminTeamMembersData = {
    teamId: string;
};

export type AdminReadAdminTeamMembersResponse = (TeamMembersPublic);

export type AdminPromoteSystemAdminData = {
    userId: string;
};

export type AdminPromoteSystemAdminResponse = (UserPublic);

export type AdminListSystemSettingsResponse = ({
    [key: string]: unknown;
});

export type AdminGetSystemSettingData = {
    key: string;
};

export type AdminGetSystemSettingResponse = (SystemSettingPublic);

export type AdminPutSystemSettingData = {
    key: string;
    requestBody: SystemSettingPut;
};

export type AdminPutSystemSettingResponse = (SystemSettingPutResponse);

export type AdminGenerateVapidKeysResponse = (VapidKeysGenerateResponse);

export type AdminGenerateSystemSettingData = {
    key: string;
};

export type AdminGenerateSystemSettingResponse = (SystemSettingGenerateResponse);

export type AuthSignupData = {
    requestBody: SignupBody;
};

export type AuthSignupResponse = (UserPublic);

export type AuthLoginData = {
    requestBody: LoginBody;
};

export type AuthLoginResponse = (UserPublic);

export type AuthLogoutResponse = (Message);

export type GithubGetGithubInstallUrlData = {
    teamId: string;
};

export type GithubGetGithubInstallUrlResponse = (InstallUrlResponse);

export type GithubGithubInstallCallbackData = {
    requestBody: InstallCallbackBody;
};

export type GithubGithubInstallCallbackResponse = (GitHubAppInstallationPublic);

export type GithubListGithubInstallationsData = {
    teamId: string;
};

export type GithubListGithubInstallationsResponse = ({
    [key: string]: unknown;
});

export type GithubDeleteGithubInstallationData = {
    installationRowId: string;
    teamId: string;
};

export type GithubDeleteGithubInstallationResponse = ({
    [key: string]: unknown;
});

export type GithubReceiveGithubWebhookResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NotificationsListNotificationsData = {
    limit?: number;
    unreadOnly?: boolean;
};

export type NotificationsListNotificationsResponse = (NotificationsPublic);

export type NotificationsUnreadCountResponse = (NotificationUnreadCount);

export type NotificationsMarkReadData = {
    notificationId: string;
};

export type NotificationsMarkReadResponse = (NotificationPublic);

export type NotificationsMarkAllReadResponse = (NotificationReadAllResponse);

export type NotificationsTriggerTestNotificationData = {
    requestBody: NotificationTestTrigger;
};

export type NotificationsTriggerTestNotificationResponse = ((NotificationPublic | null));

export type NotificationsListPreferencesResponse = (Array<NotificationPreferencePublic>);

export type NotificationsUpsertPreferenceData = {
    eventType: string;
    requestBody: NotificationPreferencePut;
};

export type NotificationsUpsertPreferenceResponse = (NotificationPreferencePublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsListTeamProjectsData = {
    teamId: string;
};

export type ProjectsListTeamProjectsResponse = (ProjectsPublic);

export type ProjectsCreateTeamProjectData = {
    requestBody: ProjectCreate;
    teamId: string;
};

export type ProjectsCreateTeamProjectResponse = (ProjectPublic);

export type ProjectsGetProjectData = {
    projectId: string;
};

export type ProjectsGetProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    projectId: string;
};

export type ProjectsDeleteProjectResponse = (void);

export type ProjectsGetProjectPushRuleData = {
    projectId: string;
};

export type ProjectsGetProjectPushRuleResponse = (ProjectPushRulePublic);

export type ProjectsPutProjectPushRuleData = {
    projectId: string;
    requestBody: ProjectPushRulePut;
};

export type ProjectsPutProjectPushRuleResponse = (ProjectPushRulePublic);

export type ProjectsOpenProjectData = {
    projectId: string;
};

export type ProjectsOpenProjectResponse = ({
    [key: string]: unknown;
});

export type PushGetVapidPublicKeyResponse = (VapidPublicKeyResponse);

export type PushSubscribeData = {
    requestBody: PushSubscriptionCreate;
};

export type PushSubscribeResponse = (PushSubscriptionPublic);

export type PushUnsubscribeData = {
    requestBody: PushSubscriptionDelete;
};

export type PushUnsubscribeResponse = (void);

export type PushListSubscriptionsResponse = (PushSubscriptionsList);

export type SessionsCreateSessionData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type SessionsCreateSessionResponse = ({
    [key: string]: unknown;
});

export type SessionsListSessionsData = {
    teamId?: (string | null);
};

export type SessionsListSessionsResponse = ({
    [key: string]: unknown;
});

export type SessionsDeleteSessionData = {
    sessionId: string;
};

export type SessionsDeleteSessionResponse = ({
    [key: string]: unknown;
});

export type SessionsGetSessionScrollbackData = {
    sessionId: string;
};

export type SessionsGetSessionScrollbackResponse = ({
    [key: string]: unknown;
});

export type TeamsReadTeamsResponse = ({
    [key: string]: unknown;
});

export type TeamsCreateTeamData = {
    requestBody: TeamCreate;
};

export type TeamsCreateTeamResponse = (TeamWithRole);

export type TeamsReadTeamMembersData = {
    teamId: string;
};

export type TeamsReadTeamMembersResponse = (TeamMembersPublic);

export type TeamsInviteToTeamData = {
    teamId: string;
};

export type TeamsInviteToTeamResponse = (InviteIssued);

export type TeamsJoinTeamData = {
    code: string;
};

export type TeamsJoinTeamResponse = (TeamWithRole);

export type TeamsUpdateMemberRoleData = {
    requestBody: MemberRoleUpdate;
    teamId: string;
    userId: string;
};

export type TeamsUpdateMemberRoleResponse = (TeamWithRole);

export type TeamsRemoveMemberData = {
    teamId: string;
    userId: string;
};

export type TeamsRemoveMemberResponse = (void);

export type TeamsUpdateTeamMirrorData = {
    requestBody: TeamMirrorPatch;
    teamId: string;
};

export type TeamsUpdateTeamMirrorResponse = (TeamMirrorVolumePublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);