/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as LayoutWorkflowsRouteImport } from './routes/_layout/workflows'
import { Route as LayoutTeamsRouteImport } from './routes/_layout/teams'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutWorkflowsWorkflowIdRouteImport } from './routes/_layout/workflows_.$workflowId'
import { Route as LayoutTeamsTeamIdRouteImport } from './routes/_layout/teams_.$teamId'
import { Route as LayoutRunsRunIdRouteImport } from './routes/_layout/runs_.$runId'
import { Route as LayoutAdminTeamsRouteImport } from './routes/_layout/admin_.teams'
import { Route as LayoutAdminSettingsRouteImport } from './routes/_layout/admin.settings'
import { Route as LayoutAdminTeamsTeamIdRouteImport } from './routes/_layout/admin.teams_.$teamId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWorkflowsRoute = LayoutWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsRoute = LayoutTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkflowsWorkflowIdRoute =
  LayoutWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows_/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTeamsTeamIdRoute = LayoutTeamsTeamIdRouteImport.update({
  id: '/teams_/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRunsRunIdRoute = LayoutRunsRunIdRouteImport.update({
  id: '/runs_/$runId',
  path: '/runs/$runId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminTeamsRoute = LayoutAdminTeamsRouteImport.update({
  id: '/admin_/teams',
  path: '/admin/teams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminSettingsRoute = LayoutAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminTeamsTeamIdRoute = LayoutAdminTeamsTeamIdRouteImport.update({
  id: '/teams_/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/teams': typeof LayoutTeamsRoute
  '/workflows': typeof LayoutWorkflowsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/admin/settings': typeof LayoutAdminSettingsRoute
  '/admin/teams': typeof LayoutAdminTeamsRoute
  '/runs/$runId': typeof LayoutRunsRunIdRoute
  '/teams/$teamId': typeof LayoutTeamsTeamIdRoute
  '/workflows/$workflowId': typeof LayoutWorkflowsWorkflowIdRoute
  '/admin/teams/$teamId': typeof LayoutAdminTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/teams': typeof LayoutTeamsRoute
  '/workflows': typeof LayoutWorkflowsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/': typeof LayoutIndexRoute
  '/admin/settings': typeof LayoutAdminSettingsRoute
  '/admin/teams': typeof LayoutAdminTeamsRoute
  '/runs/$runId': typeof LayoutRunsRunIdRoute
  '/teams/$teamId': typeof LayoutTeamsTeamIdRoute
  '/workflows/$workflowId': typeof LayoutWorkflowsWorkflowIdRoute
  '/admin/teams/$teamId': typeof LayoutAdminTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/teams': typeof LayoutTeamsRoute
  '/_layout/workflows': typeof LayoutWorkflowsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/settings': typeof LayoutAdminSettingsRoute
  '/_layout/admin_/teams': typeof LayoutAdminTeamsRoute
  '/_layout/runs_/$runId': typeof LayoutRunsRunIdRoute
  '/_layout/teams_/$teamId': typeof LayoutTeamsTeamIdRoute
  '/_layout/workflows_/$workflowId': typeof LayoutWorkflowsWorkflowIdRoute
  '/_layout/admin/teams_/$teamId': typeof LayoutAdminTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/teams'
    | '/workflows'
    | '/invite/$code'
    | '/admin/settings'
    | '/admin/teams'
    | '/runs/$runId'
    | '/teams/$teamId'
    | '/workflows/$workflowId'
    | '/admin/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/teams'
    | '/workflows'
    | '/invite/$code'
    | '/'
    | '/admin/settings'
    | '/admin/teams'
    | '/runs/$runId'
    | '/teams/$teamId'
    | '/workflows/$workflowId'
    | '/admin/teams/$teamId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/teams'
    | '/_layout/workflows'
    | '/invite/$code'
    | '/_layout/'
    | '/_layout/admin/settings'
    | '/_layout/admin_/teams'
    | '/_layout/runs_/$runId'
    | '/_layout/teams_/$teamId'
    | '/_layout/workflows_/$workflowId'
    | '/_layout/admin/teams_/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteCodeRoute: typeof InviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/workflows': {
      id: '/_layout/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof LayoutWorkflowsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams': {
      id: '/_layout/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof LayoutTeamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workflows_/$workflowId': {
      id: '/_layout/workflows_/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof LayoutWorkflowsWorkflowIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams_/$teamId': {
      id: '/_layout/teams_/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof LayoutTeamsTeamIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/runs_/$runId': {
      id: '/_layout/runs_/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof LayoutRunsRunIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin_/teams': {
      id: '/_layout/admin_/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof LayoutAdminTeamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/settings': {
      id: '/_layout/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof LayoutAdminSettingsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/teams_/$teamId': {
      id: '/_layout/admin/teams_/$teamId'
      path: '/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof LayoutAdminTeamsTeamIdRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminSettingsRoute: typeof LayoutAdminSettingsRoute
  LayoutAdminTeamsTeamIdRoute: typeof LayoutAdminTeamsTeamIdRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminSettingsRoute: LayoutAdminSettingsRoute,
  LayoutAdminTeamsTeamIdRoute: LayoutAdminTeamsTeamIdRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTeamsRoute: typeof LayoutTeamsRoute
  LayoutWorkflowsRoute: typeof LayoutWorkflowsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminTeamsRoute: typeof LayoutAdminTeamsRoute
  LayoutRunsRunIdRoute: typeof LayoutRunsRunIdRoute
  LayoutTeamsTeamIdRoute: typeof LayoutTeamsTeamIdRoute
  LayoutWorkflowsWorkflowIdRoute: typeof LayoutWorkflowsWorkflowIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTeamsRoute: LayoutTeamsRoute,
  LayoutWorkflowsRoute: LayoutWorkflowsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminTeamsRoute: LayoutAdminTeamsRoute,
  LayoutRunsRunIdRoute: LayoutRunsRunIdRoute,
  LayoutTeamsTeamIdRoute: LayoutTeamsTeamIdRoute,
  LayoutWorkflowsWorkflowIdRoute: LayoutWorkflowsWorkflowIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteCodeRoute: InviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
